name: Issues Workflow
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  Issue:
    runs-on: ubuntu-latest
    steps:
      - name: Github event name
        run: echo ${{github.event_name}}
      - name: Github event
        run: echo ${{github.event}}
